openapi: 3.1.0
info:
  title: SSL IoT-1
  summary: OpenAPI Spec for interacting wth various sensors and actuators in Smart-iLab.
  version: 1.0.0

servers:
  - url: 'http://localhost:80'

paths:
  # Apollo AIR-1
  /air-1:
    get:
      tags: ['Apollo AIR-1']
      description: Return all available Apollo AIR-1 IDs
      responses:
        '200':
          description: Successfully returned all available Apollo AIR-1 IDs
        '404':
          description: Apollo AIR-1 IDs not found

  /air-1/{id}:
    get:
      tags: ['Apollo AIR-1']
      description: Return most recent/historical data of a specific Apollo AIR-1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: time_start
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successfully returned most recent/historical data of a specific Apollo AIR-1
        '404':
          description: Unable to find specific Apollo AIR-1
        '400':
          description: Invalid Request

  /air-1/{id}/light:
    post:
      tags: ['Apollo AIR-1']
      description: Set the LED light of a specific Apollo Air 1
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: false
          schema:
            type: string
        - name: red
          in: query
          required: false
          schema:
            type: float
        - name: green
          in: query
          required: false
          schema:
            type: float
        - name: blue
          in: query
          required: false
          schema:
            type: float
        - name: brightness
          in: query
          required: false
          schema:
            type: float
      responses:
        '200':
          description: Successfully set the LED light of a specific Apollo AIR-1
        '404':
          description: Unable to find specific Apollo AIR-1
        '400':
          description: Invalid Request

  # Apollo MSR-2
  /msr-2:
    get:
      tags: ['Apollo MSR-2']
      description: Return all available Apollo MSR-2 IDs
      responses:
        '200':
          description: Successfully returned all available Apollo MSR-2 IDs
        '404':
          description: Apollo MSR-2 IDs not found

  /msr-2/{id}:
    get:
      tags: ['Apollo MSR-2']
      description: Return most recent/historical data of a specific Apollo MSR-2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: time_start
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successfully returned most recent/historical data of a specific Apollo MSR-2
        '404':
          description: Unable to find specific Apollo MSR-2
        '400':
          description: Invalid Request

  /msr-2/{id}/light:
    post:
      tags: ['Apollo MSR-2']
      description: Set the LED light of a specific Apollo MSR-2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: false
          schema:
            type: string
        - name: red
          in: query
          required: false
          schema:
            type: float
        - name: green
          in: query
          required: false
          schema:
            type: float
        - name: blue
          in: query
          required: false
          schema:
            type: float
        - name: brightness
          in: query
          required: false
          schema:
            type: float
      responses:
        '200':
          description: Successfully set the LED light of a specific Apollo MSR-2
        '404':
          description: Unable to find specific Apollo MSR-2
        '400':
          description: Invalid Request

  /msr-2/{id}/buzzer:
    post:
      tags: ['Apollo MSR-2']
      description: Play a rtttl string on the buzzer of a specific Apollo MSR-2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: mtttl_string
          in: query
          required: false
          schema:
            type: string'
      responses:
        '200':
          description: Successfully played an rtttl string on the buzzer of a specific Apollo MSR-2
        '404':
          description: Unable to find specific Apollo MSR-2
        '400':
          description: Invalid Request

  # Athom Smart Plug v2
  /smart-plug-v2:
    get:
      tags: ['Athom Smart Plug v2']
      description: Return all available Athom Smart Plug v2 IDs
      responses:
        '200':
          description: Successfully returned all available Athom Smart Plug v2 IDs
        '404':
          description: Athom Smart Plug v2 IDs not found

  /smart-plug-v2/{id}:
    get:
      tags: ['Athom Smart Plug v2']
      description: Return most recent/historical data of a specific Athom Smart Plug v2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: time_start
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successfully returned most recent/historical data of a specific Athom Smart Plug v2
        '404':
          description: Unable to find specific Athom Smart Plug v2
        '400':
          description: Invalid Request

  /smart-plug-v2/{id}/relay:
    post:
      tags: ['Athom Smart Plug v2']
      description: Set the relay of a specific Athom Smart Plug v2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully set the relay of a specific Athom Smart Plug v2
        '404':
          description: Unable to find specific Athom Smart Plug v2
        '400':
          description: Invalid Request

  # AirGradient One
  /ag-one:
    get:
      tags: ['AirGradient One']
      description: Return all available AirGradient One IDs
      responses:
        '200':
          description: Successfully returned all available AirGradient One IDs
        '404':
          description: AirGradient One IDs not found

  /ag-one/{id}:
    get:
      tags: ['AirGradient One']
      description: Return most recent/historical data of a specific AirGradient One
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: time_start
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successfully returned most recent/historical data of a specific AirGradient One
        '404':
          description: Unable to find specific AirGradient One
        '400':
          description: Invalid Request

  /ag-one/{id}/light:
    post:
      tags: ['AirGradient One']
      description: Set the LED strip of a specific AirGradient One
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: false
          schema:
            type: string
        - name: red
          in: query
          required: false
          schema:
            type: float
        - name: green
          in: query
          required: false
          schema:
            type: float
        - name: blue
          in: query
          required: false
          schema:
            type: float
        - name: brightness
          in: query
          required: false
          schema:
            type: float
      responses:
        '200':
          description: Successfully set the LED light of a specific AirGradient One
        '404':
          description: Unable to find specific AirGradient One
        '400':
          description: Invalid Request

  # Zigbee2MQTT
  /zigbee2mqtt:
    get:
      tags: ['Zigbee2MQTT']
      description: Return all available Zigbee2MQTT device and group IDs
      responses:
        '200':
          description: Successfully returned all available Zigbee2MQTT device and group IDs
        '404':
          description: Zigbee2MQTT device and group IDs not found

  /zigbee2mqtt/{id}/get:
    get:
      tags: ['Zigbee2MQTT']
      description: Return most recent/historical data of a specific Zigbee2MQTT device
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: time_start
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successfully returned most recent/historical data of a specific Zigbee2MQTT device
        '404':
          description: Unable to find specific Zigbee2MQTT device
        '400':
          description: Invalid Request

  /zigbee2mqtt/{id}/set:
    post:
      tags: ['Zigbee2MQTT']
      description: Set the state, brightness, and/or color temperature of a light or group of lights
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: false
          schema:
            type: string
        - name: brightness
          in: query
          required: false
          schema:
            type: int
        - name: color_temp
          in: query
          required: false
          schema:
            type: int
      responses:
        '200':
          description: Successfully the state, brightness, and/or color temperature of a light or group of lights
        '404':
          description: Unable to find specific light or group of lights
        '400':
          description: Invalid Request

  # Sensibo Air Pro
  /sensibo:
    get:
      tags: ['Sensibo Air Pro']
      description: Return all available Sensibo Air Pro IDs
      responses:
        '200':
          description: Successfully returned all available Sensibo Air Pro IDs
        '404':
          description: Sensibo Air Pro IDs not found

  /sensibo/{id}:
    get:
      tags: ['Sensibo Air Pro']
      description: Return most recent/historical data of a specific Sensibo Air Pro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: time_start
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: time_end
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successfully returned most recent/historical data of a specific Sensibo Air Pro
        '404':
          description: Unable to find specific Sensibo Air Pro
        '400':
          description: Invalid Request

  /sensibo/{id}/hvac:
    post:
      tags: ['Sensibo Air Pro']
      description: Set the status of a specific Sensibo Air Pro's HVAC
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hvac_mode
          in: query
          required: false
          schema:
            type: float
        - name: target_temperature
          in: query
          required: false
          schema:
            type: float
      responses:
        '200':
          description: Successfully set the status of a specific Sensibo Air Pro's HVAC
        '404':
          description: Unable to find specific Sensibo Air Pro
        '400':
          description: Invalid Request